### ISSUE TITLE
README - Project Set Up issues

### ISSUE THREAD

**Issue by rolfea** [bdougie/casper-cms-template#1]
Hello!  
  
I think I followed the set-up instruction closely, but I'm having a problem when I try to either view the current posts in the blog or create a new post.  
  
After I visit the admin page of the new site I created (alexjrolfe.netlify.com/admin) and login, clicking on the 'Blog' section on the side panel leads to an endless load. When I try to create a sample entry I get the error alert 'Failed to persist entry'.  
  
I have continuous deployment setup with netlify and github is setup as the authentication provider as well.
  
I altered the config.yml to the following:  
```
backend:
  name: github
  repo: rolfea/casper-cms-template # Path to your Github repository
  branch: master # Branch to update (master by default)
```  
  
I'm guessing I missed something in the setup. If I can get some help figuring this out, I'd be happy to submit a PR to make the documentation a little more clear.
